### PR TITLE
Safer SamplingProbabilityCorrection class

### PR DESCRIPTION
**Pull request by TimSchmeier**
I encountered `-inf` from `log(0.)` recently.

### CODE REVIEW

**Comment by TimSchmeier** [comment]
This is ready for review, I added an epsilon in case the calculation of some item probabilities approaches 0. This is common across most recommendation datasets that have a power law distribution and should result in safer gradient calculations.

**Comment by maciejkula** [comment]
Hey Tim! 

Thanks for this, let's get this merged.

**Comment by maciejkula** [comment]
Would you mind rebasing - I added some lint checks that this PR needs to pass before merging.

**Comment by TimSchmeier** [comment]
Not a problem I'll get that done this weekend.

**Comment by maciejkula** [comment]
Thank you for the fix!

**Pull request merged**
