### PR TITLE
fix factorized_top_k do not exist in tfrs.layers

### PR DESCRIPTION
**Pull request by anisayari**
replace reference to BruteForce with the correct localization in tfrs.layers.ann instead of tfrs.layers.fix factorized_top_k https://www.tensorflow.org/recommenders/api_docs/python/tfrs/layers/ann

### CODE REVIEW

**Comment by anisayari** [comment]
@googlebot I signed it!

**Comment by maciejkula** [comment]
This is an unfortunate misalignment: the colab uses an as-of-yet-unreleased version.

I will push a new release today that will fix this issue, and this PR will be unncesessary.

**Comment by maciejkula** [comment]
We've released the new version (`v0.2.0`), so this should now be fixed!

I will close this, but feel free to reopen if I'm missing something.

**Comment by anisayari** [comment]
Great thank you @maciejkula  👍 :-)

**Pull request closed without merging**
